language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly

branches:
    only:
        - master
        - /^\d+\.\d+$/

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm-nightly

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_success: |
 sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;'

notifications:
    email: pierstoval@gmail.com
